'use client';

import { useEffect, useMemo, useState } from 'react';
import { usePathname } from 'next/navigation';

export function CaregiverCalendar() {
  const [open,setOpen]=useState(true);
  const days = useMemo(() => {
    const now = new Date(); const first = new Date(now.getFullYear(), now.getMonth(), 1); const count = new Date(now.getFullYear(), now.getMonth()+1, 0).getDate(); const offset=(first.getDay()+6)%7;
    return [...Array(offset).fill(null), ...Array.from({length:count},(_,i)=>i+1)];
  }, []);
  const now = new Date(); const month=now.toLocaleDateString('th-TH',{month:'long',year:'numeric'});
  return <section className={`aha-care-calendar ${open?'is-open':'is-collapsed'}`} aria-label="ปฏิทินการดูแล"><div className="aha-care-calendar-head"><div><span>ตารางการดูแล</span><h2>ปฏิทินการดูแล</h2><p>ตรวจสอบแผนการดูแลและรายการสำคัญประจำวัน</p></div><div className="aha-care-calendar-actions"><div className="aha-care-calendar-badge">📅 <b>{now.getDate()}</b><small>วันนี้</small></div><button type="button" className="aha-care-calendar-toggle" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{open?'ซ่อน':'แสดง'}</button></div></div>{open&&<div className="aha-care-calendar-body"><div className="aha-care-calendar-month"><strong>{month}</strong><span>วันนี้ · {now.getDate()}</span></div><div className="aha-care-calendar-grid aha-care-week"><b>จ</b><b>อ</b><b>พ</b><b>พฤ</b><b>ศ</b><b>ส</b><b>อา</b></div><div className="aha-care-calendar-grid">{days.map((day,i)=><span key={`${day}-${i}`} className={day===now.getDate()?'today':''}>{day||''}</span>)}</div><div className="aha-care-calendar-legend"><span><i className="dot-blue"/>วันนี้</span><span><i className="dot-orange"/>ติดตามยา</span><span>ดูแลกันทุกวัน</span></div></div>}</section>;
}

export function DashboardShowcase() {
  return <div className="aha-care-showcase"><div className="aha-care-showcase-copy"><span>ภาพรวมการดูแล</span><h2>ข้อมูลสำคัญสำหรับผู้ดูแล</h2><p>ตรวจสอบสถานะการทานยา รายการประจำวัน และข้อมูลที่ต้องติดตามได้จากหน้าเดียว</p></div><div className="aha-care-showcase-cards"><div><b>✓</b><strong>สถานะการทานยา</strong><small>ตรวจสอบรายการที่ยืนยันแล้วและรายการที่รอดำเนินการ</small></div><div><b>◷</b><strong>รายการวันนี้</strong><small>ดูตารางและสิ่งที่ต้องติดตามในวันนี้</small></div><div><b>◎</b><strong>ข้อมูลผู้สูงอายุ</strong><small>เข้าถึงข้อมูลการดูแลที่จำเป็นได้อย่างเป็นระบบ</small></div></div></div>;
}

export function CaregiverEnhancementPanel(){
  return <div className="aha-care-enhancements"><CaregiverCalendar/><DashboardShowcase/></div>;
}

export default function AhaCaregiverEnhancements(){
  usePathname();
  return <><style jsx global>{`
    .aha-care-enhancements{width:min(1120px,calc(100% - 40px));margin:18px auto;display:flex;flex-direction:column;gap:14px}
    .aha-care-showcase{width:100%;margin:0;padding:24px 26px;border-radius:22px;background:#fff;color:#203247;position:relative;overflow:hidden;border:1px solid #dce5ec;box-shadow:0 8px 24px rgba(31,72,64,.07)}
    .aha-care-showcase:after{content:'';position:absolute;width:220px;height:220px;border-radius:50%;right:-65px;top:-100px;background:rgba(49,91,120,.06);box-shadow:-80px 150px 0 20px rgba(216,169,77,.06)}
    .aha-care-showcase-copy{position:relative;z-index:1;max-width:520px}.aha-care-showcase-copy>span{font-size:10px;font-weight:900;letter-spacing:.08em;color:#315b78}.aha-care-showcase h2{margin:6px 0 8px;font-size:28px;line-height:1.15}.aha-care-showcase h2 em{font-style:normal;color:#203247}.aha-care-showcase p{margin:0;max-width:560px;font-size:13px;line-height:1.6;color:#667789}
    .aha-care-showcase-cards{position:relative;z-index:1;display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:20px}.aha-care-showcase-cards div{padding:13px;border-radius:16px;background:#f6f8fa;border:1px solid #e4ebf0}.aha-care-showcase-cards b{display:block;font-size:18px;color:#315b78}.aha-care-showcase-cards strong{display:block;font-size:13px;margin-top:4px}.aha-care-showcase-cards small{display:block;margin-top:3px;font-size:10px;line-height:1.45;color:#748493}
    .aha-care-calendar{width:100%;margin:0;padding:20px;border:1px solid #dce6ed;border-radius:22px;background:#fff;box-shadow:0 8px 24px rgba(31,72,64,.07);color:#1f342f}.aha-care-calendar-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.aha-care-calendar-head>div:first-child>span{color:#315b78;font-size:10px;font-weight:900;letter-spacing:.12em}.aha-care-calendar-head h2{margin:3px 0 4px;font-size:22px}.aha-care-calendar-head p{margin:0;color:#6e7e8c;font-size:13px}.aha-care-calendar-actions{display:flex;align-items:center;gap:9px}.aha-care-calendar-badge{width:58px;height:62px;flex:0 0 58px;display:flex;flex-direction:column;align-items:center;justify-content:center;border-radius:16px;background:#eef4f8;color:#315b78}.aha-care-calendar-badge b{font-size:20px;line-height:1}.aha-care-calendar-badge small{font-size:9px;color:#6f807b;margin-top:3px}.aha-care-calendar-toggle{min-width:62px;height:38px;border:1px solid #d4e0e8;border-radius:11px;background:#f4f7f9;color:#294f69;font-weight:900;cursor:pointer}.aha-care-calendar-toggle:hover{background:#eef4f8}.aha-care-calendar-body{margin-top:2px}.aha-care-calendar-month{display:flex;justify-content:space-between;align-items:center;margin:16px 0 10px;padding:9px 12px;border-radius:14px;background:#f2f6f9}.aha-care-calendar-month strong{font-size:15px}.aha-care-calendar-month span{font-size:10px;color:#6e7e8c}.aha-care-calendar-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.aha-care-calendar-grid span,.aha-care-week b{min-height:38px;display:grid;place-items:center;border-radius:11px;font-size:13px}.aha-care-week b{min-height:30px;color:#85939e;font-size:10px}.aha-care-calendar-grid span{background:#fff;border:1px solid #e7edf2}.aha-care-calendar-grid span:empty{background:transparent;border-color:transparent}.aha-care-calendar-grid span.today{background:#315b78;color:#fff;border-color:#315b78;font-weight:900;box-shadow:0 5px 12px rgba(49,91,120,.20)}.aha-care-calendar-legend{display:flex;flex-wrap:wrap;gap:12px;margin-top:14px;color:#6d7d8a;font-size:10px}.aha-care-calendar-legend i{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:5px}.dot-blue{background:#315b78}.dot-orange{background:#d8a94d}.aha-care-calendar.is-collapsed{padding-top:15px;padding-bottom:15px}
    button[aria-label*="กลับ"] svg,.aha-family-back svg,.aha-profile-icon-button svg,.aha-page-back svg,.aha-back-button svg,.aha-voice-back svg,.aha-emergency-back svg{transform:rotate(180deg)!important}.aha-v3-top-actions>button:nth-child(2) .aha-v3-user-avatar{background-color:#2f6bff!important;background-size:cover!important;background-position:center!important;background-repeat:no-repeat!important}
    @media(max-width:900px){.aha-care-enhancements{width:100%;margin:14px 0}.aha-care-showcase-cards{grid-template-columns:repeat(3,minmax(0,1fr))}}
    @media(max-width:760px){.aha-care-enhancements{width:calc(100% - 20px);margin:14px auto;gap:12px}.aha-care-showcase{width:100%;padding:20px 18px;border-radius:19px}.aha-care-showcase h2{font-size:23px}.aha-care-showcase p{font-size:11px}.aha-care-showcase-cards{grid-template-columns:1fr;gap:7px}.aha-care-showcase-cards div{padding:10px}.aha-care-showcase-cards small{font-size:9px}.aha-care-calendar{width:100%;padding:16px;border-radius:19px}.aha-care-calendar-actions{gap:6px}.aha-care-calendar-badge{width:52px;height:56px;flex-basis:52px}.aha-care-calendar-toggle{min-width:58px;height:36px}.aha-care-calendar-head h2{font-size:19px}.aha-care-calendar-head p{font-size:11px}.aha-care-calendar-grid span{min-height:clamp(30px,9vw,36px);font-size:clamp(10px,3.2vw,12px)}}
    @media(max-width:420px){.aha-care-calendar-head{align-items:flex-start}.aha-care-calendar-actions{flex-direction:column;align-items:stretch}.aha-care-calendar-badge{display:none}.aha-care-calendar-toggle{min-width:60px}.aha-care-showcase{padding:17px 14px}.aha-care-showcase h2{font-size:20px}.aha-care-calendar{padding:14px}.aha-care-calendar-grid{gap:3px}}
  `}</style></>;
}
