'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import AhaIcon from '../../components/AhaIcon';
import {getSession} from '../../services/auth';
import {notificationApi} from '../../services/api';
const listOf=r=>Array.isArray(r)?r:Array.isArray(r?.data)?r.data:Array.isArray(r?.notifications)?r.notifications:[];
const iconFor=t=>String(t).includes('emergency')||String(t).includes('sos')?'warning':String(t).includes('medicine')||String(t).includes('reminder')?'pill':'bell';
export default function NotificationsPage(){
 const router=useRouter(),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);try{setItems(listOf(await notificationApi.list()))}catch(e){if(e.status===401){router.replace('/login');return}setError(e.message||'โหลดแจ้งเตือนไม่สำเร็จ')}finally{setLoading(false)}};
 useEffect(()=>{if(!getSession()?.accessToken){router.replace('/login');return}load()},[router]);
 const read=async id=>{try{await notificationApi.markRead(id);setItems(xs=>xs.map(x=>x.id===id?{...x,is_read:true}:x))}catch(e){setError(e.message)}};
 const allRead=async()=>{try{await notificationApi.markAllRead();setItems(xs=>xs.map(x=>({...x,is_read:true})))}catch(e){setError(e.message)}};
 const remove=async id=>{try{await notificationApi.remove(id);setItems(xs=>xs.filter(x=>x.id!==id))}catch(e){setError(e.message)}};
 return <div className="aha-page"><div className="aha-shell"><header className="topbar"><div className="brand"><button className="icon-btn" onClick={()=>router.push('/home')}><AhaIcon name="arrow" size={21}/></button><div className="brand-mark"><AhaIcon name="bell"/></div><span>การแจ้งเตือน</span></div><button className="btn btn-soft" onClick={allRead}><AhaIcon name="check"/> อ่านทั้งหมด</button></header><section className="hero"><div className="hero-content"><div className="eyebrow">NOTIFICATION HISTORY</div><h1>ทุกเหตุการณ์สำคัญอยู่ที่นี่</h1><p>ตรวจสอบประวัติการเตือนยาและการแจ้งเตือนของ AHA</p></div></section>{error&&<div className="error" style={{margin:'18px 0'}}>{error}</div>}<section className="card" style={{marginTop:18}}>{loading?<div className="empty">กำลังโหลด…</div>:items.length===0?<div className="empty"><AhaIcon name="bell" size={34}/><div style={{marginTop:10,fontWeight:850}}>ยังไม่มีการแจ้งเตือน</div><div>เมื่อมีเหตุการณ์ใหม่ ระบบจะแสดงที่นี่</div></div>:<div className="grid">{items.map(n=><article className={'notification-item '+(!n.is_read?'unread':'')} key={n.id}><div className="notification-icon"><AhaIcon name={iconFor(n.type)}/></div><div><div style={{fontWeight:850}}>{n.title}</div><div className="muted" style={{marginTop:4,lineHeight:1.6}}>{n.message}</div><div className="muted small" style={{marginTop:7}}>{n.created_at?new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(n.created_at)):''}</div></div><div className="actions"><button className="btn btn-soft" onClick={()=>read(n.id)} disabled={n.is_read}>{n.is_read?'อ่านแล้ว':'อ่าน'}</button><button className="btn btn-danger" onClick={()=>remove(n.id)}><AhaIcon name="trash" size={16}/></button></div></article>)}</div>}</section><nav className="footer-nav"><div className="footer-nav-inner"><button className="footer-link" onClick={()=>router.push('/home')}><AhaIcon name="home" size={20}/><span>หน้าหลัก</span></button><button className="footer-link" onClick={()=>router.push('/reminders')}><AhaIcon name="pill" size={20}/><span>ยา</span></button><button className="footer-link active"><AhaIcon name="bell" size={20}/><span>แจ้งเตือน</span></button><button className="footer-link" onClick={()=>router.push('/emergency')}><AhaIcon name="warning" size={20}/><span>ฉุกเฉิน</span></button></div></nav></div></div>
}