'use client';
import {useCallback,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import AhaIcon from '../../components/AhaIcon';
import {saveSession} from '../../services/auth';
import {authApi,notificationApi} from '../../services/api';
const listOf=r=>Array.isArray(r)?r:Array.isArray(r?.data)?r.data:Array.isArray(r?.notifications)?r.notifications:[];
const iconFor=t=>String(t).includes('emergency')||String(t).includes('sos')?'warning':String(t).includes('medicine')||String(t).includes('reminder')?'pill':'bell';
export default function NotificationsPage(){
 const router=useRouter(),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{setItems(listOf(await notificationApi.list()))}catch(e){if(e.status===401){router.replace('/login');return}setError(e.message||'โหลดแจ้งเตือนไม่สำเร็จ')}finally{setLoading(false)}},[router]);
 useEffect(()=>{let active=true;authApi.me().then(r=>{if(!active||!r?.user)return;saveSession({user:r.user});return load()}).catch(()=>{if(active)router.replace('/login')});return()=>{active=false}},[router,load]);
 const read=async id=>{try{await notificationApi.markRead(id);setItems(xs=>xs.map(x=>x.id===id?{...x,is_read:true}:x))}catch(e){setError(e.message)}};
 const allRead=async()=>{try{await notificationApi.markAllRead();setItems(xs=>xs.map(x=>({...x,is_read:true})))}catch(e){setError(e.message)}};
 const remove=async id=>{try{await notificationApi.remove(id);setItems(xs=>xs.filter(x=>x.id!==id))}catch(e){setError(e.message)}};
 return <div className="aha-page aha-notifications-page"><div className="aha-shell"><header className="topbar"><div className="brand"><button className="icon-btn aha-notifications-back" onClick={()=>router.push('/home')} aria-label="กลับหน้าหลัก"><AhaIcon name="arrow" size={21}/></button><div className="brand-mark"><AhaIcon name="bell"/></div><span>การแจ้งเตือน</span></div><button className="btn btn-soft" onClick={allRead}><AhaIcon name="check"/> อ่านทั้งหมด</button></header><section className="hero"><div className="hero-content"><div className="eyebrow">ประวัติการแจ้งเตือน</div><h1>การแจ้งเตือนของคุณ</h1><p>ตรวจสอบการเตือนยาและเหตุการณ์สำคัญย้อนหลัง</p></div></section>{error&&<div className="error" style={{margin:'18px 0'}}>{error}</div>}<section className="card" style={{marginTop:18}}>{loading?<div className="empty">กำลังโหลด…</div>:items.length===0?<div className="empty"><AhaIcon name="bell" size={34}/><div style={{marginTop:10,fontWeight:850}}>ยังไม่มีการแจ้งเตือน</div><div>เมื่อมีเหตุการณ์ใหม่ ระบบจะแสดงที่นี่</div></div>:<div className="grid">{items.map(n=><article className={'notification-item '+(!n.is_read?'unread':'')+(String(n.type).includes('emergency')?' emergency':'')} key={n.id}><div className="notification-icon"><AhaIcon name={iconFor(n.type)}/></div><div><div style={{fontWeight:850}}>{n.title}</div><div className="muted" style={{marginTop:4,lineHeight:1.6}}>{n.message}</div><div className="muted small" style={{marginTop:7}}>{n.created_at?new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(n.created_at)):''}</div></div><div className="actions"><button className="btn btn-soft" onClick={()=>read(n.id)} disabled={n.is_read}>{n.is_read?'อ่านแล้ว':'อ่าน'}</button><button className="btn btn-danger" onClick={()=>remove(n.id)}><AhaIcon name="trash" size={16}/></button></div></article>)}</div>}</section><nav className="footer-nav"><div className="footer-nav-inner"><button className="footer-link" onClick={()=>router.push('/home')}><AhaIcon name="home" size={20}/><span>หน้าหลัก</span></button><button className="footer-link" onClick={()=>router.push('/reminders')}><AhaIcon name="pill" size={20}/><span>ยา</span></button><button className="footer-link active"><AhaIcon name="bell" size={20}/><span>แจ้งเตือน</span></button><button className="footer-link" onClick={()=>router.push('/emergency')}><AhaIcon name="warning" size={20}/><span>ฉุกเฉิน</span></button></div></nav><style jsx global>{`
.aha-notifications-page{background:#f5f6f8;color:#263442}.aha-notifications-page .brand-mark{background:#fff;color:#425d73;border:1px solid #dce3e9;box-shadow:none}.aha-notifications-page .hero{background:#fff;border:1px solid #dfe5ea;box-shadow:0 8px 24px rgba(35,48,60,.06)}.aha-notifications-page .hero:before,.aha-notifications-page .hero:after{display:none}.aha-notifications-page .eyebrow{color:#60778b;letter-spacing:.06em}.aha-notifications-page .hero h1{color:#263442}.aha-notifications-page .hero p{color:#6c7a86}.aha-notifications-page .card{border-color:#dfe5ea;box-shadow:0 8px 24px rgba(35,48,60,.05)}.aha-notifications-page .notification-item{background:#fff;border-color:#e3e8ec}.aha-notifications-page .notification-item.unread{background:#f5f8fa;border-color:#cbd9e3;box-shadow:inset 3px 0 #54748d}.aha-notifications-page .notification-icon{background:#edf2f5;color:#425d73}.aha-notifications-page .aha-notifications-back svg{transform:rotate(180deg)!important}.aha-notifications-page .notification-item:has(.notification-icon){} .aha-notifications-page .notification-item.unread .notification-icon{color:#385d78}.aha-notifications-page .notification-item:has(.notification-icon svg){} .aha-notifications-page .notification-item{min-width:0;overflow:hidden}.aha-notifications-page .notification-item>div{min-width:0}.aha-notifications-page .notification-item .muted{overflow-wrap:anywhere;word-break:break-word}.aha-notifications-page .notification-item.emergency{background:#fff0f0;border:1px solid #e2555f;box-shadow:inset 5px 0 #b91c2b}.aha-notifications-page .notification-item.emergency.unread{background:#ffe7e8;border-color:#d73d49;box-shadow:inset 5px 0 #a91220}.aha-notifications-page .notification-item.emergency .notification-icon{background:#ffd9dc;color:#a91220}.aha-notifications-page .notification-item.emergency .muted{color:#71343a!important}.aha-notifications-page .notification-item.emergency>div:nth-child(2)>div:first-child{color:#991b1b}@media(max-width:760px){.aha-notifications-page .notification-item{grid-template-columns:auto minmax(0,1fr)!important;gap:10px!important;padding:14px!important}.aha-notifications-page .notification-item .actions{grid-column:1/-1;display:flex!important;justify-content:flex-end;flex-wrap:wrap}.aha-notifications-page .notification-item .actions .btn{min-width:0}.aha-notifications-page .notification-item .muted{max-width:100%;white-space:normal}}
`}</style></div></div>
}
